### ISSUE TITLE
I cannot get a tick off of me

### ISSUE THREAD

**Issue by Ratmonster04** [vemerion/Mosquitoes#1]
There is a tick on me and I cannot get it off, I have tried the swatter, the tweezers and the potions, and I still cant get it off. I think this a glitch. Btw this is on the 1.16.3 version
![2020-10-26_09 20_edited](https://user-images.githubusercontent.com/64166998/97177353-83cba400-176c-11eb-8294-4873be8f88e1.jpg)

**Comment by vemerion** [comment]
The idea is that you have to use the tweezers and release the button when the tweezers are as close to the head of the tick as possible. It works when I try it, but of course there could be some edge case where it fails. Would it be possible for you upload a short gif or video when you use the tweezers? Otherwise as a last resort I would recommend to simple remove the mod, which will obviously remove the tick.

**Comment by Ratmonster04** [comment]
ok got it off

**Comment by vemerion** [comment]
Great! I am glad the issue was able to be resolved quickly :). I presume that you got the tweezers working in the end? Anyway, I will go ahead and close this issue.
